### ISSUE TITLE
Always Redirect to Landing Page

### ISSUE THREAD

**Issue by katpas** [Jonty76/bubbles#477]
- If lost any of the info needed to go forward, redirect straight to landing page.

**Comment by rug1** [comment]
Thinking about this I'm not sure if this is going to be possible because that middle bit of the app (from select restaurant to your hamper page) is shared by both the airport and the expo app. So if someone did go directly to /basket/select-restaurant there is no way to determine what app they are on and so no way to know where to direct them to

**Comment by rug1** [comment]
On the expo app, we **always** catch if details are missing so a user cannot proceed to payment unless it is completed. I think it's going to be quite a trivial case that people are going to go to that exact url, the most important thing is that they can't proceed to payment which we've done

**Comment by rug1** [comment]
@katpas What do you think?

**Comment by katpas** [comment]
Yeah, I thought there was a reason we did it that way in the first place. Ok, I'll explain it to Jonny.
